import img from '../../assets/img/backgorund/Frame152.png'
import right from '../../assets/icons/mian.icons/main-right-btn-icons.png'
import left from '../../assets/icons/mian.icons/main-left-icons.png'
import loactionImg from '../../assets/icons/mian.icons/location.svg'
import img1 from '../../assets/icons/MainApiIcons/icons1.png'
import img2 from '../../assets/icons/MainApiIcons/icons2.png'
import img3 from '../../assets/icons/MainApiIcons/icons3.png'
import img4 from '../../assets/icons/MainApiIcons/icons4.png'
import img5 from '../../assets/icons/MainApiIcons/icons5.png'
import img6 from '../../assets/icons/MainApiIcons/icons6.png'
import GoogleImg from '../../assets/img/main/image.webp'
import Remont from '../../assets/img/backgorund/main-right-img.png';

export const mainApi = [
    {
        id: 0,
        img: img,
        right: right,
        left: left,
        mainTextP1: 'ЖК Чаркова 72',
        mainTextaction: '100 квартир от застройщика «Астон»',
        bottomTextP1: 'от 4 377 600 р',
        bottomTextP2: 'В ипотеку от 13 760 р / мес',
        topText: '3 квартал 2024 — 3 квартал 2025',
        mainRigh1text: 'Студии',
        mainRigh2text: '1-комнатные',
        mainRigh3text: '2-комнатные',
        mainCenterP: 'от 4,4 млн р',
        mainleftptext1: '3-комнатные',
        mainleftptext2: '4-комнатные +',
        mainLeftP1: 'от 4,4 млн р',
        mainLeftP2: 'от 4,4 млн р',
        mainRightBtn: ['Продукты', 'Образование', 'Медицина', 'Спорт', 'Развлечения', 'Парки'],
        imgbtn: [img1, img2, img3, img4, img5, img6],
        mainCenterLocation: 'Тюмень, Чаркова 72 — 1.1',
        mainCenterLeftbtn: 'Подробнее',
        loactionimg: loactionImg,
        MainImg: img1,
        googleImg: Remont,
        category: 'All'
    },
    {
        id: 1,
        img: img,
        right: right,
        left: left,
        mainTextP1: 'ЖК Чаркова 72',
        mainTextaction: '100 квартир от застройщика «Астон»',
        bottomTextP1: 'от 4 377 600 р',
        bottomTextP2: 'В ипотеку от 13 760 р / мес',
        topText: '3 квартал 2024 — 3 квартал 2025',
        mainRigh1text: 'Студии',
        mainRigh2text: '1-комнатные',
        mainRigh3text: '2-комнатные',
        mainCenterP: 'от 4,4 млн р',
        mainleftptext1: '3-комнатные',
        mainleftptext2: '4-комнатные +',
        mainLeftP1: 'от 4,4 млн р',
        mainLeftP2: 'от 4,4 млн р',
        mainRightBtn: ['Продукты', 'Образование', 'Медицина', 'Спорт', 'Развлечения', 'Парки'],
        imgbtn: [img1, img2, img3, img4, img5, img6],
        mainCenterLocation: 'Тюмень, Чаркова 72 — 1.1',
        mainCenterLeftbtn: 'Подробнее',
        loactionimg: loactionImg,
        MainImg: img1,
        googleImg: Remont,
        category: 'All'

    },
    {
        id: 2,
        img: img,
        right: right,
        left: left,
        mainTextP1: 'ЖК Чаркова 72',
        mainTextaction: '100 квартир от застройщика «Астон»',
        bottomTextP1: 'от 4 377 600 р',
        bottomTextP2: 'В ипотеку от 13 760 р / мес',
        topText: '3 квартал 2024 — 3 квартал 2025',
        mainRigh1text: 'Студии',
        mainRigh2text: '1-комнатные',
        mainRigh3text: '2-комнатные',
        mainCenterP: 'от 4,4 млн р',
        mainleftptext1: '3-комнатные',
        mainleftptext2: '4-комнатные +',
        mainLeftP1: 'от 4,4 млн р',
        mainLeftP2: 'от 4,4 млн р',
        mainRightBtn: ['Продукты', 'Образование', 'Медицина', 'Спорт', 'Развлечения', 'Парки'],
        imgbtn: [img1, img2, img3, img4, img5, img6],
        mainCenterLocation: 'Тюмень, Чаркова 72 — 1.1',
        mainCenterLeftbtn: 'Подробнее',
        loactionimg: loactionImg,
        MainImg: img1,
        googleImg: Remont,
        category: 'All'
    },
    {
        id: 3,
        img: img,
        right: right,
        left: left,
        mainTextP1: 'ЖК Чаркова 72',
        mainTextaction: '100 квартир от застройщика «Астон»',
        bottomTextP1: 'от 4 377 600 р',
        bottomTextP2: 'В ипотеку от 13 760 р / мес',
        topText: '3 квартал 2024 — 3 квартал 2025',
        mainRigh1text: 'Студии',
        mainRigh2text: '1-комнатные',
        mainRigh3text: '2-комнатные',
        mainCenterP: 'от 4,4 млн р',
        mainleftptext1: '3-комнатные',
        mainleftptext2: '4-комнатные +',
        mainLeftP1: 'от 4,4 млн р',
        mainLeftP2: 'от 4,4 млн р',
        mainRightBtn: ['Продукты', 'Образование', 'Медицина', 'Спорт', 'Развлечения', 'Парки'],
        imgbtn: [img1, img2, img3, img4, img5, img6],
        mainCenterLocation: 'Тюмень, Чаркова 72 — 1.1',
        mainCenterLeftbtn: 'Подробнее',
        loactionimg: loactionImg,
        MainImg: img1,
        googleImg: Remont,
        category: 'All'
    },
    {
        id: 4,
        img: img,
        right: right,
        left: left,
        mainTextP1: 'ЖК Чаркова 72 ',
        mainTextaction: '100 квартир от застройщика «Астон»',
        bottomTextP1: 'от 4 377 600 р',
        bottomTextP2: 'В ипотеку от 13 760 р / мес',
        topText: '3 квартал 2024 — 3 квартал 2025',
        mainRigh1text: 'Студии',
        mainRigh2text: '1-комнатные',
        mainRigh3text: '2-комнатные',
        mainCenterP: 'от 4,4 млн р',
        mainleftptext1: '3-комнатные',
        mainleftptext2: '4-комнатные +',
        mainLeftP1: 'от 4,4 млн р',
        mainLeftP2: 'от 4,4 млн р',
        mainRightBtn: ['Продукты', 'Образование', 'Медицина', 'Спорт', 'Развлечения', 'Парки'],
        imgbtn: [img1, img2, img3, img4, img5, img6],
        mainCenterLocation: 'Тюмень, Чаркова 72 — 1.1',
        mainCenterLeftbtn: 'Подробнее',
        loactionimg: loactionImg,
        MainImg: img1,
        googleImg: GoogleImg,
        category: 'Без отделки'
    },
    {
        id: 5,
        img: img,
        right: right,
        left: left,
        mainTextP1: 'ЖК Чаркова 72',
        mainTextaction: '100 квартир от застройщика «Астон»',
        bottomTextP1: 'от 4 377 600 р',
        bottomTextP2: 'В ипотеку от 13 760 р / мес',
        topText: '3 квартал 2024 — 3 квартал 2025',
        mainRigh1text: 'Студии',
        mainRigh2text: '1-комнатные',
        mainRigh3text: '2-комнатные',
        mainCenterP: 'от 4,4 млн р',
        mainleftptext1: '3-комнатные',
        mainleftptext2: '4-комнатные +',
        mainLeftP1: 'от 4,4 млн р',
        mainLeftP2: 'от 4,4 млн р',
        mainRightBtn: ['Продукты', 'Образование', 'Медицина', 'Спорт', 'Развлечения', 'Парки'],
        imgbtn: [img1, img2, img3, img4, img5, img6],
        mainCenterLocation: 'Тюмень, Чаркова 72 — 1.1',
        mainCenterLeftbtn: 'Подробнее',
        loactionimg: loactionImg,
        MainImg: img1, 
        googleImg: GoogleImg,
        category: 'Без отделки'
    },
    {
        id: 6,
        img: img,
        right: right,
        left: left,
        mainTextP1: 'ЖК Чаркова 72',
        mainTextaction: '100 квартир от застройщика «Астон»',
        bottomTextP1: 'от 4 377 600 р',
        bottomTextP2: 'В ипотеку от 13 760 р / мес',
        topText: '3 квартал 2024 — 3 квартал 2025',
        mainRigh1text: 'Студии',
        mainRigh2text: '1-комнатные',
        mainRigh3text: '2-комнатные',
        mainCenterP: 'от 4,4 млн р',
        mainleftptext1: '3-комнатные',
        mainleftptext2: '4-комнатные +',
        mainLeftP1: 'от 4,4 млн р',
        mainLeftP2: 'от 4,4 млн р',
        mainRightBtn: ['Продукты', 'Образование', 'Медицина', 'Спорт', 'Развлечения', 'Парки'],
        imgbtn: [img1, img2, img3, img4, img5, img6],
        mainCenterLocation: 'Тюмень, Чаркова 72 — 1.1',
        mainCenterLeftbtn: 'Подробнее',
        loactionimg: loactionImg,
        MainImg: img4,
        googleImg: Remont,
        category: 'С отделкой',
    },
    {
        id: 7,
        img: img,
        right: right,
        left: left,
        mainTextP1: 'ЖК Чаркова 72',
        mainTextaction: '100 квартир от застройщика «Астон»',
        bottomTextP1: 'от 4 377 600 р',
        bottomTextP2: 'В ипотеку от 13 760 р / мес',
        topText: '3 квартал 2024 — 3 квартал 2025',
        mainRigh1text: 'Студии',
        mainRigh2text: '1-комнатные',
        mainRigh3text: '2-комнатные',
        mainCenterP: 'от 4,4 млн р',
        mainleftptext1: '3-комнатные',
        mainleftptext2: '4-комнатные +',
        mainLeftP1: 'от 4,4 млн р',
        mainLeftP2: 'от 4,4 млн р',
        mainRightBtn: ['Продукты', 'Образование', 'Медицина', 'Спорт', 'Развлечения', 'Парки'],
        imgbtn: [img1, img2, img3, img4, img5, img6],
        mainCenterLocation: 'Тюмень, Чаркова 72 — 1.1',
        mainCenterLeftbtn: 'Подробнее',
        loactionimg: loactionImg,
        MainImg: img2,
        googleImg: Remont,
        category: 'С отделкой'
    },
    {
        id: 8,
        img: img,
        right: right,
        left: left,
        mainTextP1: 'ЖК Чаркова 72',
        mainTextaction: '100 квартир от застройщика «Астон»',
        bottomTextP1: 'от 4 377 600 р',
        bottomTextP2: 'В ипотеку от 13 760 р / мес',
        topText: '3 квартал 2024 — 3 квартал 2025',
        mainRigh1text: 'Студии',
        mainRigh2text: '1-комнатные',
        mainRigh3text: '2-комнатные',
        mainCenterP: 'от 4,4 млн р',
        mainleftptext1: '3-комнатные',
        mainleftptext2: '4-комнатные +',
        mainLeftP1: 'от 4,4 млн р',
        mainLeftP2: 'от 4,4 млн р',
        mainRightBtn: ['Продукты', 'Образование', 'Медицина', 'Спорт', 'Развлечения', 'Парки'],
        imgbtn: [img1, img2, img3, img4, img5, img6],
        mainCenterLocation: 'Тюмень, Чаркова 72 — 1.1',
        mainCenterLeftbtn: 'Подробнее',
        loactionimg: loactionImg,
        MainImg: img2,
        googleImg: Remont,
        category: 'С отделкой'
    },
    {
        id: 9,
        img: img,
        right: right,
        left: left,
        mainTextP1: 'ЖК Чаркова 72',
        mainTextaction: '100 квартир от застройщика «Астон»',
        bottomTextP1: 'от 4 377 600 р',
        bottomTextP2: 'В ипотеку от 13 760 р / мес',
        topText: '3 квартал 2024 — 3 квартал 2025',
        mainRigh1text: 'Студии',
        mainRigh2text: '1-комнатные',
        mainRigh3text: '2-комнатные',
        mainCenterP: 'от 4,4 млн р',
        mainleftptext1: '3-комнатные',
        mainleftptext2: '4-комнатные +',
        mainLeftP1: 'от 4,4 млн р',
        mainLeftP2: 'от 4,4 млн р',
        mainRightBtn: ['Продукты', 'Образование', 'Медицина', 'Спорт', 'Развлечения', 'Парки'],
        imgbtn: [img1, img2, img3, img4, img5, img6],
        mainCenterLocation: 'Тюмень, Чаркова 72 — 1.1',
        mainCenterLeftbtn: 'Подробнее',
        loactionimg: loactionImg,
        MainImg: img4,
        googleImg: Remont,
        category: 'С отделкой',
    },
    {
        id: 10,
        img: img,
        right: right,
        left: left,
        mainTextP1: 'ЖК Чаркова 72',
        mainTextaction: '100 квартир от застройщика «Астон»',
        bottomTextP1: 'от 4 377 600 р',
        bottomTextP2: 'В ипотеку от 13 760 р / мес',
        topText: '3 квартал 2024 — 3 квартал 2025',
        mainRigh1text: 'Студии',
        mainRigh2text: '1-комнатные',
        mainRigh3text: '2-комнатные',
        mainCenterP: 'от 4,4 млн р',
        mainleftptext1: '3-комнатные',
        mainleftptext2: '4-комнатные +',
        mainLeftP1: 'от 4,4 млн р',
        mainLeftP2: 'от 4,4 млн р',
        mainRightBtn: ['Продукты', 'Образование', 'Медицина', 'Спорт', 'Развлечения', 'Парки'],
        imgbtn: [img1, img2, img3, img4, img5, img6],
        mainCenterLocation: 'Тюмень, Чаркова 72 — 1.1',
        mainCenterLeftbtn: 'Подробнее',
        loactionimg: loactionImg,
        MainImg: img2,
        googleImg: Remont,
        category: 'С отделкой'
    },
    {
        id: 11,
        img: img,
        right: right,
        left: left,
        mainTextP1: 'ЖК Чаркова 72',
        mainTextaction: '100 квартир от застройщика «Астон»',
        bottomTextP1: 'от 4 377 600 р',
        bottomTextP2: 'В ипотеку от 13 760 р / мес',
        topText: '3 квартал 2024 — 3 квартал 2025',
        mainRigh1text: 'Студии',
        mainRigh2text: '1-комнатные',
        mainRigh3text: '2-комнатные',
        mainCenterP: 'от 4,4 млн р',
        mainleftptext1: '3-комнатные',
        mainleftptext2: '4-комнатные +',
        mainLeftP1: 'от 4,4 млн р',
        mainLeftP2: 'от 4,4 млн р',
        mainRightBtn: ['Продукты', 'Образование', 'Медицина', 'Спорт', 'Развлечения', 'Парки'],
        imgbtn: [img1, img2, img3, img4, img5, img6],
        mainCenterLocation: 'Тюмень, Чаркова 72 — 1.1',
        mainCenterLeftbtn: 'Подробнее',
        loactionimg: loactionImg,
        MainImg: img2,
        googleImg: Remont,
        category: 'С отделкой'
    },


    {
        id: 12,
        img: img,
        right: right,
        left: left,
        mainTextP1: 'ЖК Чаркова 72 ',
        mainTextaction: '100 квартир от застройщика «Астон»',
        bottomTextP1: 'от 4 377 600 р',
        bottomTextP2: 'В ипотеку от 13 760 р / мес',
        topText: '3 квартал 2024 — 3 квартал 2025',
        mainRigh1text: 'Студии',
        mainRigh2text: '1-комнатные',
        mainRigh3text: '2-комнатные',
        mainCenterP: 'от 4,4 млн р',
        mainleftptext1: '3-комнатные',
        mainleftptext2: '4-комнатные +',
        mainLeftP1: 'от 4,4 млн р',
        mainLeftP2: 'от 4,4 млн р',
        mainRightBtn: ['Продукты', 'Образование', 'Медицина', 'Спорт', 'Развлечения', 'Парки'],
        imgbtn: [img1, img2, img3, img4, img5, img6],
        mainCenterLocation: 'Тюмень, Чаркова 72 — 1.1',
        mainCenterLeftbtn: 'Подробнее',
        loactionimg: loactionImg,
        MainImg: img1,
        googleImg: GoogleImg,
        category: 'Без отделки'
    },
    {
        id: 13,
        img: img,
        right: right,
        left: left,
        mainTextP1: 'ЖК Чаркова 72',
        mainTextaction: '100 квартир от застройщика «Астон»',
        bottomTextP1: 'от 4 377 600 р',
        bottomTextP2: 'В ипотеку от 13 760 р / мес',
        topText: '3 квартал 2024 — 3 квартал 2025',
        mainRigh1text: 'Студии',
        mainRigh2text: '1-комнатные',
        mainRigh3text: '2-комнатные',
        mainCenterP: 'от 4,4 млн р',
        mainleftptext1: '3-комнатные',
        mainleftptext2: '4-комнатные +',
        mainLeftP1: 'от 4,4 млн р',
        mainLeftP2: 'от 4,4 млн р',
        mainRightBtn: ['Продукты', 'Образование', 'Медицина', 'Спорт', 'Развлечения', 'Парки'],
        imgbtn: [img1, img2, img3, img4, img5, img6],
        mainCenterLocation: 'Тюмень, Чаркова 72 — 1.1',
        mainCenterLeftbtn: 'Подробнее',
        loactionimg: loactionImg,
        MainImg: img1, 
        googleImg: GoogleImg,
        category: 'Без отделки'
    },
    {
        id: 14,
        img: img,
        right: right,
        left: left,
        mainTextP1: 'ЖК Чаркова 72 ',
        mainTextaction: '100 квартир от застройщика «Астон»',
        bottomTextP1: 'от 4 377 600 р',
        bottomTextP2: 'В ипотеку от 13 760 р / мес',
        topText: '3 квартал 2024 — 3 квартал 2025',
        mainRigh1text: 'Студии',
        mainRigh2text: '1-комнатные',
        mainRigh3text: '2-комнатные',
        mainCenterP: 'от 4,4 млн р',
        mainleftptext1: '3-комнатные',
        mainleftptext2: '4-комнатные +',
        mainLeftP1: 'от 4,4 млн р',
        mainLeftP2: 'от 4,4 млн р',
        mainRightBtn: ['Продукты', 'Образование', 'Медицина', 'Спорт', 'Развлечения', 'Парки'],
        imgbtn: [img1, img2, img3, img4, img5, img6],
        mainCenterLocation: 'Тюмень, Чаркова 72 — 1.1',
        mainCenterLeftbtn: 'Подробнее',
        loactionimg: loactionImg,
        MainImg: img1,
        googleImg: GoogleImg,
        category: 'Без отделки'
    },
    {
        id: 15,
        img: img,
        right: right,
        left: left,
        mainTextP1: 'ЖК Чаркова 72',
        mainTextaction: '100 квартир от застройщика «Астон»',
        bottomTextP1: 'от 4 377 600 р',
        bottomTextP2: 'В ипотеку от 13 760 р / мес',
        topText: '3 квартал 2024 — 3 квартал 2025',
        mainRigh1text: 'Студии',
        mainRigh2text: '1-комнатные',
        mainRigh3text: '2-комнатные',
        mainCenterP: 'от 4,4 млн р',
        mainleftptext1: '3-комнатные',
        mainleftptext2: '4-комнатные +',
        mainLeftP1: 'от 4,4 млн р',
        mainLeftP2: 'от 4,4 млн р',
        mainRightBtn: ['Продукты', 'Образование', 'Медицина', 'Спорт', 'Развлечения', 'Парки'],
        imgbtn: [img1, img2, img3, img4, img5, img6],
        mainCenterLocation: 'Тюмень, Чаркова 72 — 1.1',
        mainCenterLeftbtn: 'Подробнее',
        loactionimg: loactionImg,
        MainImg: img1, 
        googleImg: GoogleImg,
        category: 'Без отделки'
    },
    {
        id: 16,
        img: img,
        right: right,
        left: left,
        mainTextP1: 'ЖК Чаркова 72',
        mainTextaction: '100 квартир от застройщика «Астон»',
        bottomTextP1: 'от 4 377 600 р',
        bottomTextP2: 'В ипотеку от 13 760 р / мес',
        topText: '3 квартал 2024 — 3 квартал 2025',
        mainRigh1text: 'Студии',
        mainRigh2text: '1-комнатные',
        mainRigh3text: '2-комнатные',
        mainCenterP: 'от 4,4 млн р',
        mainleftptext1: '3-комнатные',
        mainleftptext2: '4-комнатные +',
        mainLeftP1: 'от 4,4 млн р',
        mainLeftP2: 'от 4,4 млн р',
        mainRightBtn: ['Продукты', 'Образование', 'Медицина', 'Спорт', 'Развлечения', 'Парки'],
        imgbtn: [img1, img2, img3, img4, img5, img6],
        mainCenterLocation: 'Тюмень, Чаркова 72 — 1.1',
        mainCenterLeftbtn: 'Подробнее',
        loactionimg: loactionImg,
        MainImg: img1,
        googleImg: Remont,
        category: 'All'
    },
    {
        id: 17,
        img: img,
        right: right,
        left: left,
        mainTextP1: 'ЖК Чаркова 72',
        mainTextaction: '100 квартир от застройщика «Астон»',
        bottomTextP1: 'от 4 377 600 р',
        bottomTextP2: 'В ипотеку от 13 760 р / мес',
        topText: '3 квартал 2024 — 3 квартал 2025',
        mainRigh1text: 'Студии',
        mainRigh2text: '1-комнатные',
        mainRigh3text: '2-комнатные',
        mainCenterP: 'от 4,4 млн р',
        mainleftptext1: '3-комнатные',
        mainleftptext2: '4-комнатные +',
        mainLeftP1: 'от 4,4 млн р',
        mainLeftP2: 'от 4,4 млн р',
        mainRightBtn: ['Продукты', 'Образование', 'Медицина', 'Спорт', 'Развлечения', 'Парки'],
        imgbtn: [img1, img2, img3, img4, img5, img6],
        mainCenterLocation: 'Тюмень, Чаркова 72 — 1.1',
        mainCenterLeftbtn: 'Подробнее',
        loactionimg: loactionImg,
        MainImg: img1,
        googleImg: Remont,
        category: 'All'
    },
]